### ISSUE TITLE
False positive when (multiple) hashs are involved.

### ISSUE THREAD

**Issue by Symbitic** [Scrum/remark-lint-double-link#9]
This plugin gives a false positive of saying there are double links when using hashtags.
For example:

- https://playground.babylonjs.com/#58I88I#186
- https://playground.babylonjs.com/#947JF6#0
- https://playground.babylonjs.com/#8T3YBR#2
- https://playground.babylonjs.com/#WVPVWL
- https://playground.babylonjs.com/#VXA85M#5

**Comment by Scrum** [comment]
https://github.com/sindresorhus/awesome-lint/issues/133
